# Netlify configuration for Next.js 14 static export
[build]
  # Use the custom netlify-build script from package.json
  command = "npm ci && npm run netlify-build"
  publish = "out"

# Handle client-side routing for Next.js
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

# Add headers for CSS files to ensure proper loading
[[headers]]
  for = "/_next/static/css/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "text/css"

# Add headers for all static assets
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

  ## (optional) Settings for Netlify Dev
  ## https://github.com/netlify/cli/blob/main/docs/netlify-dev.md#project-detection
  #[dev]
  #  command = "yarn start" # Command to start your dev server
  #  port = 3000 # Port that the dev server will be listening on
  #  publish = "dist" # Folder with the static content for _redirect file

  ## more info on configuring this file: https://ntl.fyi/file-based-build-config
