# Netlify configuration for Next.js 14 static export
[build]
  # Use the standard build command
  command = "npm ci && npm run build"
  publish = "out"

# Specific redirect for recipes index page
[[redirects]]
  from = "/recipes"
  to = "/recipes/index.html"
  status = 200

# Redirect all recipe detail pages to the placeholder page
# This is the key change - all recipe URLs will use the placeholder page
# which will then use client-side JavaScript to fetch the correct recipe data
[[redirects]]
  from = "/recipes/*"
  to = "/recipes/placeholder.html"
  status = 200

# For all other paths, try to serve the requested path if it exists
[[redirects]]
  from = "/*"
  to = "/:splat"
  status = 200

# Add headers for CSS files to ensure proper loading
[[headers]]
  for = "/_next/static/css/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "text/css"

# Add headers for all static assets
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

  ## (optional) Settings for Netlify Dev
  ## https://github.com/netlify/cli/blob/main/docs/netlify-dev.md#project-detection
  #[dev]
  #  command = "yarn start" # Command to start your dev server
  #  port = 3000 # Port that the dev server will be listening on
  #  publish = "dist" # Folder with the static content for _redirect file

  ## more info on configuring this file: https://ntl.fyi/file-based-build-config
