# Netlify configuration for Next.js with App Router
[build]
  command = "npm run build"
  publish = ".next"

# Use the Netlify Next.js plugin
[[plugins]]
  package = "@netlify/plugin-nextjs"

# For fallback routes in Next.js
[[redirects]]
  from = "/*"
  to = "/_ipx"
  status = 200
  force = false
  conditions = {Country = ["US"]}

  ## (optional) Settings for Netlify Dev
  ## https://github.com/netlify/cli/blob/main/docs/netlify-dev.md#project-detection
  #[dev]
  #  command = "yarn start" # Command to start your dev server
  #  port = 3000 # Port that the dev server will be listening on
  #  publish = "dist" # Folder with the static content for _redirect file

  ## more info on configuring this file: https://ntl.fyi/file-based-build-config
